name: union_app
description: Connect developers from around the globe.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  meta: ^1.3.0
  equatable: ^2.0.3
  flutter_bloc: ^7.2.0
  #reezed_annotation: ^0.14.3
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.1
  google_sign_in: ^5.1.0
  formz: ^0.4.0
  font_awesome_flutter: ^9.1.0
  flow_builder: ^0.0.4
  dots_indicator: ^2.0.0
  cloud_firestore: ^2.5.4
  firebase_storage: ^10.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  #freezed: ^0.14.5
  build_runner: ^2.1.2
  bloc_test: ^8.3.0

dependency_overrides:
  meta: ^1.7.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/intro_page/
    - assets/icons/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-ThinItalic.ttf
          style: italic
    - family: LatoBlack
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-BlackItalic.ttf
          style: italic
    - family: LatoBold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic